//Understand
export const ADD_UNDERSTAND_POINT = 'ADD_UNDERSTAND_POINT';
export const SET_UNDERSTAND_POINTS = 'SET_UNDERSTAND_POINTS';

//Is it good future?
export const ADD_GOOD_FUTURE_POINT = 'ADD_CUSTOMER_POINT';
export const SET_GOOD_FUTURE_POINTS = 'SET_CUSTOMER_POINTS';

//Is it good past?
export const SET_GOOD_PAST_METRIC = 'SET_GOOD_PAST_METRIC';
export const SET_GOOD_PAST_METRIC_YEARS = 'SET_GOOD_PAST_METRIC_YEARS';
export const SET_BASE_YEAR = 'SET_BASE_YEAR';
